change(deprecated_functions): replace cx_hash with cx_hash_no_throw a…
LedgerHQ/noise-c pull request #14
Opened 2023-06-26 12:54 UTC by ndedouhet-ledger

…nd cx_aes with cx_aes_no_throw

2023-06-26 13:46 UTC, pandouard commented on src/backend/bolos-vaultapp/hash-sha256.c
> +    cx_hash_no_throw(&(st->sha256.header), 0, data, len, NULL, 0);
Shouldn't the return status be checked?

2023-06-26 13:55 UTC, ndedouhet-ledger commented on src/backend/bolos-vaultapp/hash-sha256.c
> +    cx_hash_no_throw(&(st->sha256.header), 0, data, len, NULL, 0);
Nice catch!

2023-06-26 13:59 UTC, jbeaussart-ledger requested changes
Some functions have now a return value to check

2023-06-27 14:18 UTC, ndedouhet-ledger commented on src/backend/bolos-vaultapp/hash-sha256.c
> +    cx_hash_no_throw(&(st->sha256.header), 0, data, len, NULL, 0);
Here we will ignore return value to not break the noise design pattern

2023-06-27 14:27 UTC, jbeaussart-ledger approved these changes
LGTM

2023-06-27 14:51 UTC, merged